### ISSUE TITLE
对于自定义数据集,需要更改anchor吗?

### ISSUE THREAD

**Issue by 865315255** [fb029ed/yolov5_cpp_openvino#12]
请问,我使用自己训练的数据集,在解析网络结构get_anchors里,是否应该替换成自己的anchors?
![0](https://user-images.githubusercontent.com/67730998/123214297-9cf24380-d4f9-11eb-8887-d47a9cb0c885.PNG)

**Comment by fb029ed** [comment]
您好，建议使用kmeans算法，获取适合自己数据集的anchors。

> 请问,我使用自己训练的数据集,在解析网络结构get_anchors里,是否应该替换成自己的anchors?
> ![0](https://user-images.githubusercontent.com/67730998/123214297-9cf24380-d4f9-11eb-8887-d47a9cb0c885.PNG)

您好，建议使用kmeans算法，获取适合自己数据集的anchors。

**Comment by fb029ed** [comment]
> 请问,我使用自己训练的数据集,在解析网络结构get_anchors里,是否应该替换成自己的anchors?
> ![0](https://user-images.githubusercontent.com/67730998/123214297-9cf24380-d4f9-11eb-8887-d47a9cb0c885.PNG)

您好，建议使用kmeans算法，获取适合自己数据集的anchors。
