### ISSUE TITLE
类别输出有人弄好了吗？我预测的类别存在问题

### ISSUE THREAD

**Issue by haixiansheng** [fb029ed/yolov5_cpp_openvino#18]

**Comment by fb029ed** [comment]
> 

你好，可以看下pull requests里面的实现

**Comment by fb029ed** [comment]
> 你好，可以看下pull requests里面的实现



> _No description provided._

你好，可以看下pull requests里面的实现

**Comment by haixiansheng** [comment]
好的，感谢大神
